### ISSUE TITLE
First bubble in the FTU process has a "Back" link - should it?

### ISSUE THREAD

**Issue by flukeout** [mozilla/goggles.mozilla.org#263]
![image](https://cloud.githubusercontent.com/assets/25212/11877944/4f8ccbe8-a4a7-11e5-8c2d-ee9c453996cd.png)

If i click back, it just removes the bubble - should it return to the initial popup with the instructions instead?

cc @kristinashu

**Comment by kristinashu** [comment]
Ah good point! @Pomax can you please remove this back button?

**Comment by flukeout** [comment]
No worries, I'll do it along with the animation stuff

**Comment by Pomax** [comment]
we never actually did this, bumping

**Comment by Pomax** [comment]
as goggles has become increasingly impossible to use in its current incarnation, closing this until we actually decide to put dev hours on the project.
