### ISSUE TITLE
add detection of http resources when trying to publish

### ISSUE THREAD

**Issue by Pomax** [mozilla/goggles.mozilla.org#271]
If you publish an `http` page, chances are good you're not going to see the same thing when you load the published work because it'll be on https (so all http resources will be blocked). We might be able to warn people about this when they fire up the goggles, or when they publish.

**Comment by Pomax** [comment]
cc @hannahkane @kristinashu for possible ideas on how best to signal this to the user.

**Comment by hannahkane** [comment]
A dismissable banner at the top of the page? Copy should be brief with a link to more info. (e.g. "This remix might not look the same as the original. Learn more.") Learn more could link to a detailed page in the FAQ.

@kristinashu - what do you think?

**Comment by kristinashu** [comment]
Yup, works for me.

**Comment by Pomax** [comment]
when do we want to expose this? On goggles launch? (since it'll already know things may become problematic when it starts up)

**Comment by hannahkane** [comment]
Yeah, I'd say so. BTW, I wouldn't call this a P1. Haven't heard complaints from users or anything.

**Comment by Pomax** [comment]
I'm using a really silly styling atm, but this notice will pop up when you visit an `http` rather than `https` url now (in the `https-warning` branch):

![wergwegrwreg](https://cloud.githubusercontent.com/assets/177243/13022775/5b5d5fe6-d198-11e5-95de-9a20f38ac865.png)

This clearly needs some nicer styling, but also some good copy to explain the problem, perhaps with some links to good Sumo or other pages that explain why this happens (and that this is one of the fundamental behaviours of the web)

**Comment by jgmac1106** [comment]
"Everyone is working to make sure the web is secure. This means encouraging the use of HTTPS and not HTTP (the s stands for secure).

Unfortunately this also causes X-Ray Goggles to break when you remix a page that uses the old HTTP.

We at Mozilla Learning are busy working on a solution. Until then make sure the pages you remix start with https and not http."

That would be my draft of  wording choice. The other was way too technical for X-ray users. 

Not sure where solution could fit in priority but it should be pretty high. Right now end users just see Mozilla Learning putting out a broken product. 

I would fix soon or disable until fixed.

**Comment by hannahkane** [comment]
@jgmac1106 - I really like your wording. Thanks!

And, as we just discussed on a call, I'd agree this is higher priority now. Have gotten more questions about this since my earlier comment.

**Comment by jgmac1106** [comment]
"Everyone wants a more secure web." Loses the passive voice.

**Comment by kristinashu** [comment]
@Pomax we could style it something like the green bar at the top of https://thimble.webmaker.org/

Except it would be taller and we could use the pink since it will probably stand out the most.

**Comment by Pomax** [comment]
Too subtle, this needs to be a really clear message before people get started, at the very least until we've turned https://github.com/mozilla/teach.mozilla.org/issues/1825 into actionable issues.

**Comment by kristinashu** [comment]
How about we do a modal like in "Step 1: activate the X-Ray Goggles" on the FTU page? So the page darkens and the text is in a white box.

**Comment by Pomax** [comment]
Oh, that's a good idea!

**Comment by Pomax** [comment]
It turns out that updating goggles, publish, and the routing infrastructure, so that http pages actually publish *on* http, with the remix link giving an http:// rather than https:// page, obviating the need for this warning.

I will file a new issue to figure out the best way to expose the teaching/learning moment when people visit their remix, because the top bar can now say something like "The web is moving to https, have a look at what your remix looks like via https, by the way it'll look all kinds of wrong, because of mixed content, ask your treacher/click here to learn about that"
