### ISSUE TITLE
Install analytics on goggles.mozilla.org landing page

### ISSUE THREAD

**Issue by cassiemc** [mozilla/goggles.mozilla.org#277]
As per the communications inventory, it seems there are no google analytics on goggles? It's possible this note is from before the new version of goggles launched. We should fix that and/or give access to @adamlofting. I would also appreciate access. cc @Pomax @hannahkane

**Comment by Pomax** [comment]
We were only using analytics on our pages, which have all changed and moved since we added that, so no metrics are currently getting collected. Adam should already have access, he wrote https://github.com/mozilla/x-ray-goggles/blob/master/public/js/google-analytics.js

**Comment by adamlofting** [comment]
I think... and this is from a conversation maybe 2 years ago so it might be wrong... but we couldn't add GA to the actual use of Goggles because it's not loading from our web page (if you're hacking on another site for example).

We did have some data about the old (new) goggles landing page (when we refreshed it on webmaker.org), and how many people clicked the install button though.

**Comment by adamlofting** [comment]
@Pomax I think that google-analytics.js file came across from the project when it was hosted on webmaker.org (and I updated it when I did an update across all our sites) but it's not actually being used on https://goggles.mozilla.org so we're not tracking any data.

I'll file a ticket for that now... we'll need to setup a new profile in GA to store that data too now that it's on a new domain.

**Comment by Pomax** [comment]
Yeah putting it in the library itself won't work all that well, but we can add it to where the user hits our express server for things like "requesting the library .js file", "requesting the publication .html file" etc.

**Comment by adamlofting** [comment]
I've filed a ticket to get the property setup in GA, then I'll have a look at the implementation (likely next week):

https://bugzilla.mozilla.org/show_bug.cgi?id=1251290

**Comment by Pomax** [comment]
nice! give me a shout when you do.

**Comment by davidascher** [comment]
Update:

Here is the snippet to add to the site:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new
Date();a=s.createElement(o),
 
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49796218-41', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by Pomax** [comment]
GA code added to the current Homepage and FTU master layout template, and pushed to production

**Comment by davidascher** [comment]
seeing numbers in analytics dashboard, closing.  thanks @Pomax
