### ISSUE TITLE
Cert on goggles.mozilla.org is missing intermediate CA

### ISSUE THREAD

**Issue by arve0** [mozilla/goggles.mozilla.org#306]
See [report on ssl labs](https://www.ssllabs.com/ssltest/analyze.html?d=goggles.mozilla.org&latest).

The whole certificate chain is not sent, missing DigiCert's EV server intermediate CA.

Not sure this is the right place to report, the [twitter link](https://twitter.com/mozteach) on goggles.mozilla.org is pointing to a suspended account at twitter. Please point me in the right direction, if this is the wrong place.

**Comment by cadecairos** [comment]
I'll fix this up.

**Comment by Pomax** [comment]
filed https://github.com/mozilla/goggles.mozilla.org/issues/307 for the twitter link issue, good find.

**Comment by cadecairos** [comment]
OK, The intermediate cert is installed now. A+!
