### ISSUE TITLE
Problem with edit panel

### ISSUE THREAD

**Issue by voltel** [mozilla/goggles.mozilla.org#309]
Windows 8, Firefox 50.1.0, Tutorial with sliced pictures of fox, penguin and something else - the editing pannel blinks but is not properly displayed. It's either gone all the way, or there are only Update/Cancel buttons.

**Comment by Pomax** [comment]
I cannot reproduce this on windows 10 with firefox 50.1.0, are there any more details that you can supply? (are you running any extensions that might interfere with content manipulation etc?)

![ftu](https://cloud.githubusercontent.com/assets/177243/22341432/a60ac23e-e3a5-11e6-8699-dbb1991e94fe.gif)

**Comment by voltel** [comment]
I ran Firefox without AddOns - the editing panel in X-Ray Goggles worked just fine. Eventually, I installed the last Firefox 51.0.1 and deleted some of the old AddOns and the panel works.  But then Publishing feature didn't work which I guess in the topic for another issue ticket.
