### ISSUE TITLE
The code box closes prematurely

### ISSUE THREAD

**Issue by amhemesh** [mozilla/goggles.mozilla.org#310]
When you select any element in the page a box appears which closes automatically as soon as I click in any areas inside the box. If the box gets closed automatically then how am I suppose to re-write the code and publish it? Please fix it ASAP. Thank You

**Comment by Pomax** [comment]
can you provide us with some more details? Which device, operating system, and browser are you using, and on which site does this happen (just one, some, or any)?

**Comment by amhemesh** [comment]
I'm currently using X-Ray Goggles in Win 10 OS, Chrome browser and the OS is running on a PC. 
And this is happening in all the websites visited not just any! I thought it might be because of my extensions but i checked that too and it's occurring even after disabling them. So please help..

**Comment by Pomax** [comment]
Hm, I also have a PC with Windows 10 and Chrome, but I'm seeing a different error, where the edit window is 100% height. Let me fix that first, and then we can retry to see if your original problem is still there, and if so, whether I can reproduce it (it looks like I can type in the textbox just fine, it's just positioned all wrong)

**Comment by Pomax** [comment]
I have updated the height problem, can you see whether your original problem still exists? (I can use goggles in a new Chrome install just fine now, it pops up the edit box, but it does not disappear if I try to click on it and then type in it)

**Comment by amhemesh** [comment]
Nope, it's still happening to me! The edit window just closes automatically every time within 2-3 seconds.

**Comment by Pomax** [comment]
And you are certain you are not running any extensions? What happens when you delete your current bookmarklet, then close chrome and rerun it using `chrome  –no-extensions` explicitly, then you visit goggles.mozilla.org and grab the bookmarklet anew, and then try to remix a different website, like http://news.ycombinator.com or something?

**Comment by amhemesh** [comment]
Yeah, it's working fine now. One of the chrome extension of name 'Wappalyzer' was causing the trouble. It's working hassle free now. Thank you so much 👍

**Comment by Pomax** [comment]
glad to hear it's resolved!
